CREATE DATABASE lap2
go
USE lap2
go
CREATE TABLE USER_ACCOUNT(
CusID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
CusUser VARCHAR(25) NOT NULL,
CusPass	VARCHAR(32) NOT NULL,
CusName NVARCHAR(50) NOT NULL,
CusPhone VARCHAR(12)  NULL UNIQUE,
CusAdd NVARCHAR(255)  NULL,
CusEmail VARCHAR(50) NULL,
CusFacebook NVARCHAR(150) NULL,
CusSkyper NVARCHAR(150) NULL,
CusStatus TINYINT NOT NULL
)
go
CREATE TABLE Employee(
EMP_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
EMP_NAME NVARCHAR(50) NOT NULL,
EMP_NO NVARCHAR(20) NOT NULL,
HIRE_DATE DATE NOT NULL,
SALARY FLOAT NOT NULL,
DEPT_ID INT NOT NULL
)
go
